name: Train MNIST Model on Vertex AI

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  ARTIFACT_REPO_NAME: ${{ secrets.GCP_ARTIFACT_REPO_NAME}}
  REGION: asia-northeast3
  IMAGE: mnist-trainer

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Build and push Docker image to Artifact Registry
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev
          docker build -t $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO_NAME/$IMAGE:${{ steps.slug.outputs.sha }} .
          docker push $REGION-docker.pkg.dev/$PROJECT_ID/$ARTIFACT_REPO_NAME/$IMAGE:${{ steps.slug.outputs.sha }}
