name: Deployment (Vertex AI)

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  ARTIFACT_REPO_NAME: ${{ secrets.GCP_ARTIFACT_REPO_NAME}}
  REGION: asia-northeast3
  IMAGE: mnist-trainer

jobs:
  deploy-to-vertex-ai:
    runs-on: ubuntu-latest
    steps:
      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Submit Vertex AI training job
        run: |
          gcloud ai custom-jobs create \
            --project ${{ env.PROJECT_ID }} \
            --region=${{ env.REGION }} \
            --display-name=mnist-training-job \
            --worker-pool-spec=machine-type=n1-standard-4,executor-image-uri=asia-docker.pkg.dev/vertex-ai/training/pytorch-gpu.1-13.py310:latest,local-package-path=.,python-module=trainer \
            --args="--model-dir=gs://${{ secrets.GCP_BUCKET_NAME }}/models"
