name: Train MNIST Model on Vertex AI

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  IMAGE: mnist-trainer

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha::$(git rev-parse --short HEAD)"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build and push Docker image to GCR
        run: |
          gcloud auth configure-docker
          docker build -t gcr.io/$PROJECT_ID/$IMAGE:${{ steps.slug.outputs.sha }} .
          docker push gcr.io/$PROJECT_ID/$IMAGE:${{ steps.slug.outputs.sha }}

  deploy-to-vertex-ai:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Submit Vertex AI training job
        run: |
          gcloud ai custom-jobs create \
            --region=us-central1 \
            --display-name=mnist-training-job \
            --worker-pool-spec=machine-type=n1-standard-4,image-uri=gcr.io/$PROJECT_ID/$IMAGE:${{ steps.slug.outputs.sha }},local-package-path=. \
            --args="--model-dir=gs://${{ secrets.GCP_BUCKET_NAME }}/models"

